package Client.Network;


public enum RequestType {
    
    INSERTUSER,
    CHECKPASSWORD,
    GETCURRENTUSER,
    GETALLUSERS,
    ADDFOLLOWER,
    GETCHATLIST,
    STARTCHAT,
    GETCHATBETWEENUSERS,
    SENDMESSAGESCHAT,
    GETALLFOLLOWERS,
    GETUSERSTATUS,
    HEARTBEAT,
    GETLASTMSG,
    CREATEPOST,
    CREATECOMMENT,
    GETALLPOSTS,
    GETALLCOMMENTS,
    GETALLFOLLOWING,
    GETPOSTSUSER,
    GETCOMMENTSPOST,
    INSERTLIKE

}
