package Server.Network;


public enum RequestTypeService {
    INSERTUSER,
    CHECKPASSWORD,
    GETCURRENTUSER,
    GETALLUSERS,
    ADDFOLLOWER,
    GETCHATLIST,
    GETUSERBYID,
    STARTCHAT,
    GETCHATBETWEENUSERS,
    SENDMESSAGESCHAT,
    GETALLFOLLOWERS,
    GETUSERSTATUS
}